# Copyright 2024 Amazon.com, Inc. or its affiliates.

FROM public.ecr.aws/lambda/python:3.11 as ingest

# Install yum deps
RUN yum -y upgrade
RUN yum -y install gcc ca-certificates

# Install python deps deps
RUN pip3 install stac_fastapi.opensearch stac_fastapi.types

# Copy the function code to the LAMBDA_TASK_ROOT directory
ADD . ${LAMBDA_TASK_ROOT}

# Install the package
RUN pip3 install .

# Set entry point
CMD ["aws.osml.data_intake.ingest_processor.handler"]
