# Copyright 2024 Amazon.com, Inc. or its affiliates.

FROM public.ecr.aws/lambda/python:3.11 as stac

RUN yum -y upgrade && \
    yum -y install gcc ca-certificates && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN pip3 install --no-cache-dir stac_fastapi.core stac_fastapi.opensearch[server] stac_fastapi.types mangum

EXPOSE 8080

CMD ["stac_fastapi.opensearch.app.handler"]
