# Copyright 2024 Amazon.com, Inc. or its affiliates.

name: osml_data_intake
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.11.6
  - conda-forge::boto3=1.34.99
  - conda-forge::gdal=3.8.3
  - conda-forge::proj=9.3.1
  - conda-forge::pip=24.0
  - pip:
      - boto3==1.34.104
      - osml-imagery-toolkit==1.3.0
      - stac_fastapi.types==3.0.0a3
      - stac_fastapi.opensearch==3.0.0a2
      - python-json-logger==2.0.7
