name: docker build & publish

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  REGISTRY: awsosml
  INGEST: ${{ github.event.repository.name }}-ingest
  STAC: ${{ github.event.repository.name }}-stac
  INTAKE: ${{ github.event.repository.name }}-intake

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Set Docker Push Flag
        run: |
          [[ "${{ github.event_name }}" =~ ^(push|release|workflow_dispatch|workflow_call)$ ]] && echo "push=true" >> $GITHUB_ENV || echo "push=false" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: meta-ingest
        with:
          images: ${{ env.REGISTRY }}/${{ env.INGEST }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{raw}},enable=${{ github.event_name == 'release' }}
            type=raw,value=nightly-dev,enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
            type=raw,value={{date 'YYYYMMDD-hhmmss' tz='UTC'}},enable=${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.ingest
          push: ${{ env.push }}
          tags: ${{ steps.meta-ingest.outputs.tags }}
          labels: ${{ steps.meta-ingest.outputs.labels }}
      - uses: docker/metadata-action@v5
        id: meta-stac
        with:
          images: ${{ env.REGISTRY }}/${{ env.STAC }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{raw}},enable=${{ github.event_name == 'release' }}
            type=raw,value=nightly-dev,enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
            type=raw,value={{date 'YYYYMMDD-hhmmss' tz='UTC'}},enable=${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.stac
          push: ${{ env.push }}
          tags: ${{ steps.meta-stac.outputs.tags }}
          labels: ${{ steps.meta-stac.outputs.labels }}
      - uses: docker/metadata-action@v5
        id: meta-intake
        with:
          images: ${{ env.REGISTRY }}/${{ env.INTAKE }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{raw}},enable=${{ github.event_name == 'release' }}
            type=raw,value=nightly-dev,enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
            type=raw,value={{date 'YYYYMMDD-hhmmss' tz='UTC'}},enable=${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.intake
          push: ${{ env.push }}
          tags: ${{ steps.meta-intake.outputs.tags }}
          labels: ${{ steps.meta-intake.outputs.labels }}
