name: docker publish

on:
  workflow_call:

env:
  REGISTRY: awsosml
  INGEST: ${{ github.event.repository.name }}_ingest
  STAC: ${{ github.event.repository.name }}_stac
  INTAKE: ${{ github.event.repository.name }}_intake


jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.INGEST }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.ingest
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.STAC }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.stac
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.INTAKE }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.intake
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
